CREATE TABLE BOOK (
  ID INTEGER PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  GENRE_ID INTEGER,
  ISBN VARCHAR(13),
  PAGES INTEGER,
  PUBLISHER_ID INTEGER,
  PUBLISHED_DATE CHAR(10),
  LANG VARCHAR(50)
);

CREATE TABLE AUTHOR (
  ID INTEGER PRIMARY KEY,
  LAST_NAME VARCHAR(255),
  FIRST_NAME VARCHAR(255)
);

CREATE TABLE BOOK_AUTHOR (
  ID INTEGER PRIMARY KEY,
  BOOK_ID INTEGER NOT NULL,
  AUTHOR_ID INTEGER NOT NULL
);
