#!/bin/bash
node node_modules/swig/bin/swig.js render ./examples/counter/jquery/index.swig > ./examples/counter/jquery/index.html
node node_modules/swig/bin/swig.js render ./examples/counter/react/index.swig > ./examples/counter/react/index.html
node node_modules/swig/bin/swig.js render ./examples/library/template/index-mithril.swig > ./examples/library/index-mithril.html
node node_modules/swig/bin/swig.js render ./examples/library/template/index-react.swig > ./examples/library/index-react.html
node node_modules/swig/bin/swig.js render ./examples/random-gif/template/index.swig > ./examples/random-gif/index.html
node node_modules/swig/bin/swig.js render ./examples/rocket-launcher/react/index.swig > ./examples/rocket-launcher/react/index.html
node node_modules/swig/bin/swig.js render ./examples/rocket-launcher/vanillajs/index.swig > ./examples/rocket-launcher/vanillajs/index.html
node node_modules/swig/bin/swig.js render ./examples/temperatures/template/index-h.swig > ./examples/temperatures/index-h.html
node node_modules/swig/bin/swig.js render ./examples/temperatures/template/index-jsx.swig > ./examples/temperatures/index-jsx.html
node node_modules/swig/bin/swig.js render ./examples/todo-list/template/index-inferno.swig > ./examples/todo-list/index-inferno.html
node node_modules/swig/bin/swig.js render ./examples/todo-list/template/index-react.swig > ./examples/todo-list/index-react.html
node node_modules/swig/bin/swig.js render ./examples/todomvc/template/index-mithril.swig > ./examples/todomvc/index-mithril.html
node node_modules/swig/bin/swig.js render ./examples/todomvc/template/index-react.swig > ./examples/todomvc/index-react.html
node node_modules/swig/bin/swig.js render ./examples/todomvc/template/index-snabbdom.swig > ./examples/todomvc/index-snabbdom.html
