node node_modules\swig\bin\swig.js render .\examples\counter\jquery\index.swig > .\examples\counter\jquery\index.html
node node_modules\swig\bin\swig.js render .\examples\counter\react\index.swig > .\examples\counter\react\index.html
node node_modules\swig\bin\swig.js render .\examples\library\mithril\index.swig > .\examples\library\mithril\index.html
node node_modules\swig\bin\swig.js render .\examples\library\react\index.swig > .\examples\library\react\index.html
node node_modules\swig\bin\swig.js render .\examples\random-gif\index-m.swig > .\examples\random-gif\index-m.html
node node_modules\swig\bin\swig.js render .\examples\random-gif\index-react.swig > .\examples\random-gif\index-react.html
node node_modules\swig\bin\swig.js render .\examples\rocket-launcher\react\index.swig > .\examples\rocket-launcher\react\index.html
node node_modules\swig\bin\swig.js render .\examples\rocket-launcher\vanillajs\index.swig > .\examples\rocket-launcher\vanillajs\index.html
node node_modules\swig\bin\swig.js render .\examples\temperatures\index-h.swig > .\examples\temperatures\index-h.html
node node_modules\swig\bin\swig.js render .\examples\temperatures\index-jsx.swig > .\examples\temperatures\index-jsx.html
node node_modules\swig\bin\swig.js render .\examples\todo-list\index-inferno.swig > .\examples\todo-list\index-inferno.html
node node_modules\swig\bin\swig.js render .\examples\todo-list\index-react.swig > .\examples\todo-list\index-react.html
node node_modules\swig\bin\swig.js render .\examples\todomvc\index-mithril.swig > .\examples\todomvc\index-mithril.html
node node_modules\swig\bin\swig.js render .\examples\todomvc\index-react.swig > .\examples\todomvc\index-react.html
node node_modules\swig\bin\swig.js render .\examples\todomvc\index-snabbdom.swig > .\examples\todomvc\index-snabbdom.html
