{% extends '../index-common.swig' %}
{% block title %}React{% endblock %}
{% block variant %}react{% endblock %}
{% block ext %}jsx{% endblock %}
{% block type %}type="text/babel" {% endblock %}
{% block content %}
<script src="/public/lib/browser.min.js"></script>
<script src="/public/lib/react-15.1.0.js"></script>
<script src="/public/lib/react-dom-15.1.0.js"></script>
<script src="/public/lib/meiosis-react.min.js"></script>
{% endblock %}
