{% extends '../index-common.swig' %}
{% block title %}VanillaJs{% endblock %}
{% block content %}
<script src="/public/lib/meiosis-vanillajs.min.js"></script>
<script src="/examples/todomvc/common/postRender.js"></script>
<script src="/examples/todomvc/vanillajs/view.js"></script>
<script src="/examples/todomvc/vanillajs/ready.js"></script>
<script src="/examples/todomvc/vanillajs/main.js"></script>
{% endblock %}
