{% extends '../index-common.swig' %}
{% block title %}VanillaJs{% endblock %}
{% block content %}
<script src="/public/lib/meiosis-vanillajs.min.js"></script>
<script src="/examples/todomvc/common/todoInput/postRender.js"></script>
<script src="/examples/todomvc/vanillajs/header/view.js"></script>
<script src="/examples/todomvc/vanillajs/header/ready.js"></script>
<script src="/examples/todomvc/vanillajs/todoItem/view.js"></script>
<script src="/examples/todomvc/vanillajs/todoItem/ready.js"></script>
<script src="/examples/todomvc/vanillajs/main/view.js"></script>
<script src="/examples/todomvc/vanillajs/footer/view.js"></script>
<script src="/examples/todomvc/vanillajs/footer/ready.js"></script>
<script src="/examples/todomvc/vanillajs/todoapp/view.js"></script>
<script src="/examples/todomvc/vanillajs/root/view.js"></script>
<script src="/examples/todomvc/vanillajs/app.js"></script>
{% endblock %}
